### ISSUE TITLE
Error (related to Python3 strings vs. bytes?)

### ISSUE THREAD

**Issue by iskandr** [timodonnell/pyopen#4]
``` sh
$ pyopen https://gist.githubusercontent.com/armish/bacfda412dc87d0984cb13a8ffa10c8b/raw/98b02625aadf807c13581b214b52a706490081f1/20160715-e6-windowsize8.csv

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/pyopen", line 11, in <module>
    sys.exit(run())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyopen/command.py", line 43, in run
    go(args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyopen/command.py", line 68, in go
    local_file = web.maybe_download(filename_or_url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyopen/web.py", line 25, in maybe_download
    return download(url_or_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyopen/web.py", line 33, in download
    suffix=url.split("/")[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyopen/temp_files.py", line 15, in tempfile_path
    fd.write(contents)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tempfile.py", line 399, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
```

**Comment by timodonnell** [comment]
I think this is fixed now (and update pypi), try again?
